OAK-32: Drop MicroKernel.dispose()
fixed regression:
 
 Running org.apache.jackrabbit.mk.wrapper.VirtualRepositoryWrapperTest
 java.lang.IllegalArgumentException: instance was not created by this factory
 	at org.apache.jackrabbit.mk.MicroKernelFactory.disposeInstance(MicroKernelFactory.java:211)
 	at org.apache.jackrabbit.mk.wrapper.VirtualRepositoryWrapper.dispose(VirtualRepositoryWrapper.java:231)
 	at org.apache.jackrabbit.mk.MicroKernelFactory$3.dispose(MicroKernelFactory.java:146)
 	at org.apache.jackrabbit.mk.MicroKernelFactory.disposeInstance(MicroKernelFactory.java:207)
 	at org.apache.jackrabbit.mk.wrapper.VirtualRepositoryWrapperTest.tearDown(VirtualRepositoryWrapperTest.java:71)


git-svn-id: https://svn.apache.org/repos/asf/jackrabbit/oak/trunk@1346965 13f79535-47bb-0310-9956-ffa450edef68