OAK-3470: Utils.estimateMemoryUsage has a NoClassDefFoundError when Mongo is not being used
git-svn-id: https://svn.apache.org/repos/asf/jackrabbit/oak/trunk@1724597 13f79535-47bb-0310-9956-ffa450edef68